Repository zemiguel20/SMT-Project, pull requests merged in 2023-01, with the labels that each got.

#5 Obstacle placer
  assets/music/EnV - Paladin.mp3
  assets/music/EnV - Paladin.mp3.import
  assets/objects/ObjectPlacer.tscn
  assets/sounds/switch-sound.mp3
  assets/sounds/switch-sound.mp3.import
  scenes/Main.tscn
  scripts/ObstaclePlacer.gd
  scripts/Player.gd
Labels: feature

#6 Axe trap
  assets/axe/Axe.gd
  assets/axe/Axe.tscn
  assets/axe/Handle.png
  assets/axe/Handle.png.import
  assets/axe/Trap_Axe.png
  assets/axe/Trap_Axe.png.import
  assets/axe/axe_wave.wav
  assets/axe/axe_wave.wav.import
  assets/rope-cut/RopeCut.gd
  assets/rope-cut/RopeCut.tscn
  assets/rope-cut/cutting_rope_1.wav
  assets/rope-cut/cutting_rope_1.wav.import
  assets/spikes/Spikes.gd
  assets/spikes/Spikes.tscn
  test/AxeTest.tscn
  test/test-tools/dummy-player/DummyPlayer.tscn
Labels: feature, gameplay

#10 ObstacleHandler update
  ObjectHandler.tscn
  scenes/Main.tscn
  scripts/ObstacleHandler.gd
Labels: gameplay

#13 Win-lose screen
  assets/player/Player.tscn
  project.godot
  scenes/GameOver.tscn
  scenes/Main.tscn
  scenes/autoload/GameController.tscn
  scripts/GameController.gd
  scripts/GameOver.gd
  scripts/LevelLogic.gd
  scripts/LevelSelector.gd
  scripts/MainMenu.gd
  scripts/Pause.gd
Labels: interface, feature

#12 Added enemy obstacle
  ObstacleHandler.tscn
  assets/enemy/Enemy.tscn
  assets/enemy/animations/enemy44_0.png
  assets/enemy/animations/enemy44_0.png.import
  assets/enemy/animations/enemy44_1.png
  assets/enemy/animations/enemy44_1.png.import
  assets/enemy/animations/enemy44_2.png
  assets/enemy/animations/enemy44_2.png.import
  assets/enemy/animations/enemy44_3.png
  assets/enemy/animations/enemy44_3.png.import
  assets/enemy/animations/enemy44_4.png
  assets/enemy/animations/enemy44_4.png.import
  assets/enemy/animations/enemy44_5.png
  assets/enemy/animations/enemy44_5.png.import
  assets/enemy/animations/enemy44_6.png
  assets/enemy/animations/enemy44_6.png.import
  assets/enemy/animations/enemy44_7.png
  assets/enemy/animations/enemy44_7.png.import
  assets/enemy/enemy_3.wav
  assets/enemy/enemy_3.wav.import
  assets/enemy/enemy_death.mp3
  assets/enemy/enemy_death.mp3.import
  assets/enemy/temp_dead.png
  assets/enemy/temp_dead.png.import
  project.godot
  scripts/ObstacleHandler.gd
  scripts/Player.gd
  scripts/obstacles/Enemy.gd
Labels: feature

#17 Change menu labels and add a third levelButton
  scenes/LevelSelector.tscn
  scenes/MainMenu.tscn
  scripts/LevelSelector.gd
Labels: interface

#20 Fix death_counter and timer for finishing the level
  scenes/Main.tscn
  scripts/GameOver.gd
  scripts/LevelLogic.gd
Labels: bug

#24 Fix sfx axe slide
  assets/axe/Axe.tscn
  assets/enemy/Enemy.tscn
  assets/player/Player.tscn
  assets/spikes/spikes_pixel.png
  assets/spikes/spikes_pixel.png.import
  scenes/autoload/GameController.tscn
Labels: gameplay

#26 readded enemy sfx on queue
  assets/enemy/Enemy.tscn
  assets/enemy/EnemyGrowlSFX_2.mp3
  assets/enemy/EnemyGrowlSFX_2.mp3.import
  assets/player/Player.tscn
  scripts/obstacles/Enemy.gd
Labels: bug

#27 action cooldown and attack hitbox changes
  assets/player/Player.tscn
  scripts/Player.gd
  scripts/player_states/AttackState.gd
Labels: gameplay
